name: kuzat
description: KUZAT universal video player.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.14.0
  youtube_player_iframe: ^6.0.2
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
